[package]
name = "eatmemory"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.22.5"
libc = "0.2.112"
structopt = "0.3.25"
